package parte2.mensajes;

public enum TipoMensaje {
	MENSAJE_CONEXION,
	MENSAJE_CONFIRMACION_CONEXION,
	MENSAJE_LISTA_USUARIOS,
	MENSAJE_CONFIRMACION_LISTA_USUARIOS,
	MENSAJE_CERRAR_CONEXION,
	MENSAJE_CONFIRMACION_CERRAR_CONEXION,
	MENSAJE_PEDIR_FICHERO,
	MENSAJE_EMITIR_FICHERO,
	MENSAJE_PREPARADO_CLIENTESERVIDOR,
	MENSAJE_PREPARADO_SERVIDORCLIENTE,
	MENSAJE_AGREGAR_FICHEROS,
	MENSAJE_CONFIRMACION_AGREGAR_FICHEROS,
	MENSAJE_ELIMINAR_FICHEROS,
	MENSAJE_CONFIRMACION_ELIMINAR_FICHEROS,
	MENSAJE_ERROR_CONEXION,
	MENSAJE_ERROR_NOEXISTEFICHERO
}
